# Generated by Django 3.1 on 2020-08-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_provincebudgetbulk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProvinceBudgetBulk',
        ),
    ]
