# Generated by Django 3.1 on 2020-09-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualexpenditure',
            name='office_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='totalbudget',
            name='office_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
