# Generated by Django 3.1 on 2020-09-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200903_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='pics'),
        ),
    ]
