# Generated by Django 3.1 on 2020-09-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200903_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='pics')),
                ('missions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='pics')),
                ('link', models.URLField(blank=True, null=True)),
                ('anydiscription', models.TextField()),
            ],
        ),
    ]
