# Generated by Django 3.1 on 2020-09-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aboutmission_aboutpartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmission',
            name='missions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutmission',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='aboutpartner',
            name='anydiscription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
