# Generated by Django 3.1 on 2020-09-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200904_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmission',
            name='photo',
        ),
    ]
