# Generated by Django 3.1 on 2020-09-04 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_aboutmission_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPartner',
        ),
    ]
