# Generated by Django 3.1 on 2020-09-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200904_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincesource',
            name='budget',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provincesource',
            name='year',
            field=models.ForeignKey(blank=True, help_text='Please select a recent year... ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data7', to='core.year'),
        ),
    ]
