# Generated by Django 3.1 on 2020-09-07 05:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200907_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=250),
        ),
    ]
