# Generated by Django 3.1 on 2020-09-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200907_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincebudget',
            name='actual_expenditure',
            field=models.ManyToManyField(help_text='<p style="color:blue;font-size:25px;">Please select only one value at a time <p>', to='core.ActualExpenditure'),
        ),
        migrations.AlterField(
            model_name='provincebudget',
            name='total_budget',
            field=models.ManyToManyField(help_text='<p style="color:blue;font-size:25px;">Please select only one value at a time <p>', to='core.TotalBudget'),
        ),
    ]
