# Generated by Django 3.1 on 2020-09-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200910_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraNecessaryDAta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overallpopulation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='province',
            name='revenue_collected',
        ),
    ]
