# Generated by Django 3.1 on 2020-09-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200910_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuicerBaseSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
