# Generated by Django 3.1 on 2020-09-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_juicerbasesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JuicerBaseSettings',
        ),
    ]
