# Generated by Django 3.1 on 2020-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200910_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='per_capital_income',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
