# Generated by Django 3.1 on 2020-09-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200910_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='revenue_collected',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
