# Generated by Django 3.1 on 2020-09-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200915_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extranecessarydata',
            old_name='overallpopulation',
            new_name='overallbudget',
        ),
    ]
