# Generated by Django 3.1 on 2020-09-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200916_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='list_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
