# Generated by Django 3.1 on 2020-09-16 12:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200916_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='list_title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
